### ISSUE TITLE
사고 및 도로 돌발 상황 기능

### ISSUE THREAD

**Issue by seminchoi** [SMU-GradPoodle/SMU-Navi-back#13]
## Description
사고가 발생했을 때, 사고 정보를 테이블에 추가하는 기능 구현

## Todo
- [x] 사고 api 호출 메서드 구현
- [x] 사고 지점 좌표와 기존 좌표를 비교하는 로직 구현
- [x] 거리 차이가 일정 거리 이하일 때 사고 정보를 등교길에 추가
- [x] Accident 엔티티 구현

## ETC
기타 주의점
